### ISSUE TITLE
Plumbing existing rooms in Matrix side?

### ISSUE THREAD

**Issue by RaitoBezarius** [GearKite/MatrixZulipBridge#4]
Hi there, do you think this is realistic to enable plumbing existing rooms or do you think there are fundamental hurdles to do that?

**Comment by GearKite** [comment]
That is on my TODO list, I just don't know when I'll get to it, but it doesn't sound that hard.

**Comment by GearKite** [comment]
[Added](https://github.com/GearKite/MatrixZulipBridge/compare/5a866eb14a666227ee7b2d7a33349db2f9a9699a...d547fa3a0f7a1d4f17ad1ab8f45b8e2f670e8902)
